### ISSUE TITLE
mbrshipend field

### ISSUE THREAD

**Issue by sarangtc** [Larian77/Openbiblio#53] opened 2024-10-06 09:02 UTC
there is a mbrshipend in the latest commit for MemberQuery.php, but this field is not in any upgrade or starting sql. Need to figure out what happened.

**Comment by Larian77** [comment] 2024-10-07 07:21
Yes, I introduced the field at some point in version 5 in the German version with a simple database addition without adapting the routines. I thought it was already added in version 0.7 by the maintainers of openbiblio at that time. I'll have another look at it.

**Comment by 375michael40veit** [comment] 2024-10-11 20:51
@sarangtc @Larian77 
Almost all bugfixes for 0.8.1 are reproducible, many thanks to @sarangtc. However, this error shown here is not (yet) completely comprehensible to me.
A memebership end can be set.
- In the staff area: The membership expiry time is displayed when the member profile is called up.
- In the member area: This time is also shown in the member profile, but not clearly marked or indicated.

What else should the membership end do?

**Comment by 375michael40veit** [comment] 2024-10-12 00:08
@sarangtc @Larian77 
bug fixed: Installing english sample version. So I think, it isn't necessary to exclude mbrshipend in file MemberQuery.php

**Comment by sarangtc** [comment] 2024-10-13 12:41
OK, my db must have been out of date, it was not there a few years back, and is not in any of the upgrade scripts.

I do not see any actions for members who have surpassed their end date.

**Comment by sarangtc** [comment] 2024-10-13 12:50
New Member form labels this "Membership Ends"
![image](https://github.com/user-attachments/assets/436bf5b7-2bba-4bcc-a975-b2e50864811a)
and the member view page labels this "paid until" (which is both inconsistent with the above image and not title case as the other labels in the table
![image](https://github.com/user-attachments/assets/6be8b058-08a7-49cc-ad20-e674b19f6ef9)

**Comment by Larian77** [comment] 2024-10-13 15:15
A brief explanation: 
The mbrshipend field can be filled or empty. We have members of the association who can always borrow without an end date (in which case the field is empty). There are also (mainly) users who pay for a month, half a year or a whole year, for whom the end date is relevant because they can no longer borrow after that.
In the German version, both fields (at least in 0.8) are still called ‘bezahlt bis’ (paid until)

**Comment by Larian77** [comment] 2024-10-13 15:31
@375michael40veit @sarangtc But if I see it correctly, mbrshipend should already be added in the 0.7.1 update function if it was missing before or am I seeing it wrong (just had a quick look over it, didn't search exactly)

**Comment by sarangtc** [comment] 2024-10-13 17:26
Regarding the `mbrshipend` field can be filled or empty:
The member.sql in the 0.8.1 folder states that this cannot be null! So we need to change that then.
![image](https://github.com/user-attachments/assets/7c36d878-31d2-4d13-8de0-2f66de4588be)

and regarding `mbrshipend` being in the 0.7.1 update function, cannot see it anywhere in the UpgradeQuery.php class or in the update.php
![image](https://github.com/user-attachments/assets/774e265f-742e-44ab-b474-d29461b071cd)
![image](https://github.com/user-attachments/assets/df47093f-1f94-48a6-b15e-9e90d5f1de7c)

**Comment by Larian77** [comment] 2024-10-13 17:37
Sorry, my fault, if it's empty it isn't NULL its '0000-00-00'

**Comment by sarangtc** [comment] 2024-10-14 02:07
I couldn't find these functions, could you tell me where they are located?

**Comment by 375michael40veit** [comment] 2024-11-23 23:40
Membership End is used, for example, in mbr_view.php (note) or in reports under member search.
In the member view (mbr_account.php) there is no hint if mbrshipend has expired.

There is no sql command in UpgradeQuery.php to add the membership column.
Are there any other columns missing besides this column?

I can still add this in UpgradeQuery.php under function _upgrade071_e. Then it would be included in the 0.8.1 version. But how does it get into the 0.7.x and 0.8.0 versions?
@Larian77 Do you still have code here from earlier versions?

**Comment by 375michael40veit** [comment] 2024-11-29 22:43
@Larian77  @sarangtc 
I have now created the mbrshipend column in version 0.8.1 for the update from 0.6, 0.7 and 0.8.0 to 0.8.1.

Independently of this, I ask myself whether the column must necessarily be set to “NOT NULL” in the database? When a new member is created, if a value is not set, the value 0000-00-00 is created and set in the database.

**Comment by 375michael40veit** [comment] 2024-12-07 22:23
I would closed this bug. It works with DEFAULT NOT NULL. In my opinion, however, the setting NOT NULL could be removed.

**Closed by 375michael40veit** 2024-12-07 22:23 UTC
